# Generated by Django 5.2.7 on 2025-11-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_petition_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='harm',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='party_involved',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='evidence',
            name='rule_violation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
